namespace View
{
    public enum MapObjectImage
    {
        None,
        Tree,
        Mine,
        Farm,
        Llama,
        Chupacabra,
        Sloth,
        DeadLlama,
        DeadSloth,
        DeadChupacabra,
        Worker,
        MainHall,
        Wall,
        Construction,
        Soldier,
        Barrack,
        Boss,
        DeadBoss,
        Hero,
        Doctor,
        Tower,
        MedicalTent,
        Rock,
        Rolls,
        DeadRolls,
        Bullet,
        TreeCut,
        GunMan
    };
}
